image: docker:19.03

services:
  - docker:dind

stages:
  - build
  - sonarqube-check
  - push
  - deploy
  - review
  - staging
  - production
  - cleanup

variables:
  DOCKER_IMAGE: "${CI_PROJECT_PATH}:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
  DOMAIN: butterflycluster.com

cache:
  paths:
    - .m2/repository

build-job:
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - echo "Compiling the code..."
    - mvn -B clean install -DskipTests
  artifacts:
    paths:
      - target/*.jar
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

sonarqube-check:
  stage: sonarqube-check
  image: maven:3-eclipse-temurin-17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar
  allow_failure: true
  only:
    - merge_requests
    - master
    - main
    - develop


push-job:
  stage: push
  image: docker:19.03
  services:
    - docker:dind
  script:
    - echo "Building and pushing Docker image..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" https://index.docker.io/v1/
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  needs:
    - build-job
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

.deploy: &deploy
  image: dtzar/helm-kubectl:3.3.4
  before_script:
    - apk add --no-cache gettext
    - echo "$KUBECONFIG_CONTENT" > /tmp/kubeconfig
    - export KUBECONFIG=/tmp/kubeconfig
  script:
    - echo "Setting namespace..."
    - NAMESPACE="$CI_PROJECT_NAME"
    - echo "Deploying application..."
    - kubectl create namespace $NAMESPACE 2>/dev/null || echo "Namespace $NAMESPACE already exists."
    - kubectl config set-context --current --namespace=$NAMESPACE
    - envsubst < ./kubernetes/deployment.yaml | kubectl apply -f -
    - envsubst < ./kubernetes/service.yaml | kubectl apply -f -
    - envsubst < ./kubernetes/ingress.yaml | kubectl apply -f -

review:
  <<: *deploy
  stage: review
  variables:
    APP: review-$CI_COMMIT_REF_NAME
    APP_HOST: $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$DOMAIN
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.$DOMAIN
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

stop-review:
  <<: *deploy
  stage: cleanup
  script:
    - kubectl delete all -l app=$APP --namespace $NAMESPACE
  variables:
    APP: review-$CI_COMMIT_REF_NAME
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: manual

staging:
  <<: *deploy
  stage: staging
  variables:
    APP: staging
    APP_HOST: $CI_PROJECT_NAME-staging.$DOMAIN
  environment:
    name: staging
    url: http://$CI_PROJECT_NAME-staging.$DOMAIN
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

production:
  <<: *deploy
  stage: production
  variables:
    APP: production
    APP_HOST: $CI_PROJECT_NAME.$DOMAIN
  environment:
    name: production
    url: http://$CI_PROJECT_NAME.$DOMAIN
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
