apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    gitlab.com/project-slug: ${{ (values.destination.owner + "/" + values.destination.repo) | dump | replace('%2F', '/') }}
    backstage.io/techdocs-ref: dir:.
    gitlab.com/jobs: 'Deploy:DEFAULT_JOB,Start:START_JOB,Stop:STOP_JOB'
    backstage.io/kubernetes-id: ${{values.component_id | dump}}
    nexus-repository-manager/config.title: 'Docker Image'
    nexus-repository-manager/docker.image-name: nexus/repository/dev-docker/${DOCKER_IMAGE}
    sonarqube.org/project-key: ${SONAR_PROJECT_KEY}

spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
