apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    backstage.io/kubernetes-id: {{ .Values.backstageLabels.kubernetesId | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
      {{- include "deployment.selectorLabels" . | nindent 6 }}
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
