apiVersion: v1
kind: Service
metadata:
  name: {{ include "deployment.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    backstage.io/kubernetes-id: {{ .Values.backstageLabels.kubernetesId | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
  selector:
      {{- include "deployment.selectorLabels" . | nindent 6 }}
      app: {{ .Values.appLabels.app | quote }}
      backstage.io/kubernetes-id: {{ .Values.backstageLabels.kubernetesId | quote }}
