apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-ts
  title: Create React App Template
  description: Create a new Create React App project
  tags:
    - nodejs
    - typescript
spec:
  owner: "group:default/engineering"
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - component_id
        - owner
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - eros.butterflycluster.com
    - title: Create Secrets
      required:
        - SONARQUBE_API_TOKEN
        - DOCKER_REPO_USER
        - DOCKER_REPO_PASSWORD
        - KUBE_USER
        - KUBE_PASSWORD
      properties:
        SONARQUBE_API_TOKEN:
          title: SonarQube Project Key
          type: string
          description: SonarQube Project Key
          ui:field: Secret
        DOCKER_REPO_USER:
          title: Docker Repo User
          type: string
          description: Docker Repo User
          ui:field: Secret
        DOCKER_REPO_PASSWORD:
          title: Docker Repo Password
          type: string
          description: Docker Repo Password
          ui:field: Secret
        KUBE_USER:
          title: Kubernetes User
          type: string
          description: Kubernetes User
          ui:field: Secret
        KUBE_PASSWORD:
          title: Kubernetes Password
          type: string
          description: Kubernetes Password
          ui:field: Secret
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .gitlab-ci.yml
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts:
          - eros.butterflycluster.com
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
        
    - id: create-vault-secrets
      name: Store Secrets in Vault
      action: custom:create-vault-secrets
      input:
        component_id: ${{ parameters.component_id }}
        secrets:
          sonarQubeProjectKey: ${{ parameters.sonarQubeProjectKey }}
          dockerRepoUser: ${{ parameters.dockerRepoUser }}
          dockerRepoPassword: ${{ parameters.dockerRepoPassword }}
          kubeUser: ${{ parameters.kubeUser }}
          kubePassword: ${{ parameters.kubePassword }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}